Traceback (most recent call last):
  File "example_exudate.py", line 128, in <module>
    p = multiprocessing.Process(target=calc_model, args=(ords[r][i],ords[r][i+1],q,))
IndexError: index 3 is out of bounds for axis 0 with size 3
Process Process-1:
Traceback (most recent call last):
  File "/opt/python-3.8.3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/python-3.8.3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
TypeError: calc_model() takes 2 positional arguments but 3 were given
Process Process-2:
Traceback (most recent call last):
  File "/opt/python-3.8.3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/python-3.8.3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
TypeError: calc_model() takes 2 positional arguments but 3 were given
